services:
  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3333:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/demo
      - OTLP_SERVICE_NAME=backend
      - OTLP_SERVICE_VERSION=1.0
      - OTLP_JAEGER_TRACES_ENDPOINT=http://jaeger:4318/v1/traces
      - OTLP_JAEGER_METRICS_ENDPOINT=http://jaeger:4318/v1/metrics
    depends_on:
      - database
    command: ["bash", "-c", "chmod u+x /app/launch.sh && /app/launch.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/graphql"]
      interval: 10s
      timeout: 10s
      retries: 12
      start_period: 30s

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:3000"
    depends_on:
      - backend

  database:
    build: ./docker/database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo
    volumes:
      - database_data:/var/lib/postgresql/data
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
    environment:
      - LOG_LEVEL=debug

volumes:
  database_data:
